Update Russian translation
dnSpyEx/dnSpy pull request #294
Opened 2024-02-05 16:56 UTC by geokar2006

2024-02-05 18:41 UTC, MadProbe approved these changes
I have done through this PR and as a Russian I generally approve these changes.
My comments are purely editorial and can be discarded in favor of compressing sentences so text fits on screen better, if applicable.

2024-02-05 18:41 UTC, MadProbe commented on Extensions/dnSpy.Debugger/dnSpy.Debugger/Properties/dnSpy.Debugger.Resources.ru.resx
> +    <value>Включите поддержку отладки только моего кода</value>
Would it be better if this was "Включите поддержку отладки только для моего кода"?

2024-02-05 18:41 UTC, MadProbe commented on Extensions/ILSpy.Decompiler/dnSpy.Decompiler.ILSpy.Core/Properties/dnSpy.Decompiler.ILSpy.Core.Resources.ru.resx
> +    <value>Декомпилировать calli в выражение вызова</value>
Do you think that "Декомпилировать calli в виде выражения вызова" would be better here?
This is good enough anyway though.

2024-02-05 18:56 UTC, ElektroKill requested changes

2024-02-05 18:56 UTC, ElektroKill commented on Extensions/dnSpy.Analyzer/Properties/dnSpy.Analyzer.Resources.ru.resx
> +</root>
Undo changes to the file endings too (in many other files!)

2024-02-05 18:56 UTC, ElektroKill commented on Extensions/ILSpy.Decompiler/dnSpy.Decompiler.ILSpy.Core/Properties/dnSpy.Decompiler.ILSpy.Core.Resources.ru.resx
> +    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
Please undo whitespace changes in all the files (in other files too)

2024-02-05 18:57 UTC, geokar2006 commented on Extensions/dnSpy.Debugger/dnSpy.Debugger/Properties/dnSpy.Debugger.Resources.ru.resx
> +    <value>Включите поддержку отладки только моего кода</value>
First translation was rough and through a translator. I forgot to fix translation after translator. I will change to "Включить поддержку отладки только моего кода".

2024-02-05 19:06 UTC, geokar2006 commented on Extensions/ILSpy.Decompiler/dnSpy.Decompiler.ILSpy.Core/Properties/dnSpy.Decompiler.ILSpy.Core.Resources.ru.resx
> +    <value>Декомпилировать calli в выражение вызова</value>
I think your variant is more accurate, I will change to it.

2024-02-06 18:53 UTC, ElektroKill approved these changes

2024-02-06 18:54 UTC, merged

2026-01-15 22:37 UTC, familiapixuruco-sys commented
eu queria sem os arquivos