Add chinese translation
dnSpyEx/dnSpy pull request #337
Opened 2024-07-02 14:39 UTC by zuoyuanchun

Add chinese translation for CloseAllFrameworkAssembliesCommand

2024-07-09 13:09 UTC, UlyssesWu commented on Extensions/dnSpy.Debugger/dnSpy.Debugger/Properties/dnSpy.Debugger.Resources.zh-CN.resx
> +    <value>启用 "调试代码过滤"</value>
请使用VS中的表达方式，“调试代码过滤”并没有更好地表达这个意思。
![image](https://github.com/dnSpyEx/dnSpy/assets/4312781/a6dbe307-6183-4dfa-85f8-e72392f30d19)

2024-07-10 07:57 UTC, zuoyuanchun commented on Extensions/dnSpy.Debugger/dnSpy.Debugger/Properties/dnSpy.Debugger.Resources.zh-CN.resx
> +    <value>启用 "调试代码过滤"</value>
非常感谢,已提交修改

2024-07-10 17:06 UTC, UlyssesWu approved these changes

2024-07-10 17:06 UTC, UlyssesWu approved these changes

2024-07-13 03:41 UTC, UlyssesWu requested changes
No obvious problem for other CN translations.

> 1. Deleted spaces in some resource files.

👎 Personally, I disagree with it. These spaces are always there when Visual Studio creates the resx file. There's no need to remove them, unless a code style rule is set by maintainers.

> 2. Replaced "\n" with "\r\n" in some resource files (replaced OA with 0D 0A).

👍 OK.

> 3. Added some untranslated strings (Chinese and some Russian).
> 4. To facilitate comparison of missing translation entries, I adjusted the code order (with the default language resource file as a reference).
> 5. Some Russian strings are relatively long, and I am worried that they will exceed the display part of the control, so I did not translate them. I hope friends who know Russian can help translate them.
> 6. My non-native language level is very poor, so I use Google for comparison and translation. Of course, for some common words in some software, I refer to them as references.

👎 Why not just waiting for a native Russian speaker to translate them? Especially when your PR name is "Add chinese translation". If you insist to add Russian translations, I'd suggest you to create another PR.

2024-07-13 03:41 UTC, UlyssesWu commented on Extensions/dnSpy.Debugger/dnSpy.Debugger/Properties/dnSpy.Debugger.Resources.zh-CN.resx
> +    <value>无法确定目标文件的位数。调试可能会导致不需要的或者不受控制的图像执行。
由于image（映像）一词引发误解颇多，如果有替代说法，尽量使用替代说法。

> 无法确定目标文件的位数。调试可能会导致**非预期的**或者不受控制的**程序映像**执行。

2024-07-13 03:41 UTC, UlyssesWu commented on Extensions/dnSpy.Debugger/dnSpy.Debugger/Properties/dnSpy.Debugger.Resources.zh-CN.resx
> +建议使用 32 位 dnSpy 调试 32 位图像，使用 64 位 dnSpy 调试 64 位图像。
建议使用 32 位 dnSpy 调试 32 位**程序**，使用 64 位 dnSpy 调试 64 位**程序**。

2024-07-13 04:36 UTC, zuoyuanchun commented on Extensions/dnSpy.Debugger/dnSpy.Debugger/Properties/dnSpy.Debugger.Resources.zh-CN.resx
> +    <value>无法确定目标文件的位数。调试可能会导致不需要的或者不受控制的图像执行。
已修改,非常感谢您的建议

2024-07-13 04:36 UTC, zuoyuanchun commented on Extensions/dnSpy.Debugger/dnSpy.Debugger/Properties/dnSpy.Debugger.Resources.zh-CN.resx
> +建议使用 32 位 dnSpy 调试 32 位图像，使用 64 位 dnSpy 调试 64 位图像。
已修改,非常感谢您的建议

2024-07-13 18:53 UTC, UlyssesWu approved these changes

2024-07-16 21:13 UTC, merged