Add SnapLayout Options support for Win11
dnSpyEx/dnSpy pull request #345
Opened 2024-07-15 10:58 UTC by SlimeNull

Add SnapLayout Options support for Win11

![image](https://github.com/user-attachments/assets/c3cd7296-d6b7-46c5-8df2-be6657f1116b)

2024-07-29 18:47 UTC, ElektroKill commented
Hello,

Sorry for the late response.

I like the idea of adding the support for the Win 11 snap layout feature, however, I'd prefer if this was directly integrated into dnSpy code base. I do not want to depend on additional WPF dependencies.

If this can be done cleanly and cleanly integrated into dnSpy codebase, I'm all for such a change. Please let me know if you are willing to undergo this change.

2024-07-31 08:33 UTC, SlimeNull commented
OK, I'll copy the code directly into the dnSpy repository so that it doesn't have to reference the library.

2024-08-01 16:55 UTC, ElektroKill requested changes
Please correct the code style issues I mentioned in the review, furthermore, would it be possible to isolate the code required for the Snap layouts features and remove the code for other features like rounded corners (already implemented in dnSpy) and others like backdrop, caption styling, etc? preferably the PR should include only the code necessary for the snaplayouts feature. It will make the code much easier to read as it will only contain the necessary logic!

Let me know what you think of these suggestions.

2024-08-01 16:55 UTC, ElektroKill commented on dnSpy/dnSpy/Controls/WinSysButton.cs
> +
Empty new line after opening brace, please remove it.

2024-08-01 16:55 UTC, ElektroKill commented on dnSpy/dnSpy/Lib/EleCho.WpfSuite/Utilities/WindowOption.NativeMethods.cs
> +				// Token: 0x04000368 RID: 872
Remove these comments which are decompiler artifact.

2024-08-02 07:20 UTC, SlimeNull commented
Fixed : )

2024-08-02 07:28 UTC, SlimeNull commented
If there's anything else you'd like to change, please let me know.

2024-08-07 08:53 UTC, ElektroKill approved these changes

2024-08-07 08:53 UTC, merged

2024-08-07 08:53 UTC, ElektroKill commented
Thanks!